-- USERS AND AUTHENTICATION
CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR UNIQUE NOT NULL check(email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  "password_hash" VARCHAR NOT NULL,
  "role" INT NOT NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP NULL
);

CREATE TABLE "addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "full_name" VARCHAR NOT NULL,
  "phone" VARCHAR NOT NULL,
  "street" VARCHAR NOT NULL,
  "city" VARCHAR NOT NULL,
  "state" VARCHAR,
  "country" VARCHAR NOT NULL,
  "zip_code" VARCHAR NOT NULL,
  "is_default" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP NULL
);

CREATE TABLE "password_resets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "token_hash" VARCHAR UNIQUE NOT NULL,
  "expires_at" TIMESTAMP NOT NULL,
  "used" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CATALOG
CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR UNIQUE NOT NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP NULL
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "price" DECIMAL(10, 2) NOT NULL check(price >= 0),
  "description" text NOT NULL,
  "is_enabled" BOOLEAN NOT NULL DEFAULT true,
  "category_id" INT NOT NULL REFERENCES "categories"("id") ON DELETE RESTRICT,
  "created_by" INT NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP NULL
);

CREATE TABLE "product_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" INT NOT NULL REFERENCES "products"("id") ON DELETE CASCADE,
  "image_url" VARCHAR NOT NULL,
  "is_primary" BOOLEAN NOT NULL DEFAULT false,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP NULL
);

-- USER ENGAGEMENT
CREATE TABLE "likes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "product_id" INT NOT NULL REFERENCES "products"("id") ON DELETE CASCADE,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "product_id" INT NOT NULL REFERENCES "products"("id") ON DELETE CASCADE, 
  "rating" INT NOT NULL check(rating >= 1 AND rating <= 5),
  "comment" text,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" TIMESTAMP NULL
);

-- INVENTORY
CREATE TABLE "inventory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" INT NOT NULL UNIQUE REFERENCES "products"("id") ON DELETE CASCADE,
  "quantity" INT NOT NULL DEFAULT 0 check(quantity >= 0),
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- SHOPPING CART
CREATE TABLE "carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
  "status" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" INT NOT NULL REFERENCES "carts"("id") ON DELETE CASCADE,
  "product_id" INT NOT NULL REFERENCES "products"("id") ON DELETE RESTRICT,
  "quantity" INT NOT NULL check(quantity > 0),
  "sub_total" DECIMAL(10, 2) NOT NULL check(sub_total >= 0),
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ORDERS AND PAYMENTS
CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" INT NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,
  "status" INT NOT NULL,
  "total_amount" DECIMAL(10, 2) NOT NULL check(total_amount >= 0),
  "shipping_address_id" INT NOT NULL REFERENCES "addresses"("id") ON DELETE RESTRICT,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" INT NOT NULL REFERENCES "orders"("id") ON DELETE CASCADE,
  "product_id" INT NOT NULL REFERENCES "products"("id") ON DELETE RESTRICT,
  "product_name" VARCHAR NOT NULL,
  "quantity" INT NOT NULL check(quantity > 0),
  "price" DECIMAL(10, 2) NOT NULL check(price >= 0),
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" INT NOT NULL REFERENCES "orders"("id") ON DELETE RESTRICT,
  "stripe_payment_intent" VARCHAR NOT NULL,
  "amount" DECIMAL(10, 2) NOT NULL check(amount > 0),
  "status" INT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "stripe_webhook_events" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" VARCHAR UNIQUE NOT NULL,
  "event_type" VARCHAR NOT NULL,
  "payload" JSON NOT NULL,
  "processed" BOOLEAN NOT NULL DEFAULT false,
  "received_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for unique items
CREATE UNIQUE INDEX idx_product_images_primary 
  ON "product_images" ("product_id", "is_primary") 
  WHERE "is_primary" = true AND "deleted_at" IS NULL;

CREATE UNIQUE INDEX idx_unique_like_product 
  ON "likes" ("user_id", "product_id");
CREATE UNIQUE INDEX idx_unique_review_user_product 
  ON "reviews" ("user_id", "product_id") 
  WHERE "deleted_at" IS NULL;
CREATE UNIQUE INDEX idx_unique_cart_items 
  ON "cart_items" ("cart_id", "product_id");

-- For search and filters in products
CREATE INDEX idx_products_name  
  ON "products" ("name") 
  WHERE "deleted_at" IS NULL;
CREATE INDEX idx_products_price 
  ON "products" ("price") 
  WHERE "deleted_at" IS NULL;
CREATE INDEX idx_products_enable_category 
  ON "products" ("is_enabled", "category_id") 
  WHERE "deleted_at" IS NULL;

-- For search in users
CREATE INDEX idx_users_email 
  ON "users" ("email");

-- For search user addresses
CREATE INDEX idx_addresses_user_id 
  ON "addresses" ("user_id") 
  WHERE "deleted_at" IS NULL;

-- For get product metadata
CREATE INDEX idx_reviews_product_id 
  ON "reviews" ("product_id");
CREATE INDEX idx_product_images_product_id 
  ON "product_images" ("product_id") 
  WHERE "deleted_at" IS NULL;
CREATE INDEX idx_product_likes 
  ON "likes" ("product_id");

-- For get user cart status
CREATE INDEX idx_cart_user_status 
  ON "carts" ("user_id" , "status");

-- For get product to cart_item
CREATE INDEX idx_cart_item_product_id 
  ON "cart_items" ("product_id");

-- For search order payment and filter payments by status
CREATE INDEX idx_payments_order_id 
  ON "payments" ("order_id");
CREATE INDEX idx_payments_status 
  ON "payments" ("status");

-- For search user orders and orders information
CREATE INDEX idx_user_id_orders 
  ON "orders" ("user_id");
CREATE INDEX idx_orders_status 
  ON "orders" ("status");

-- For get product to order_items 
CREATE INDEX idx_order_order_id 
  ON "order_items" ("order_id");
CREATE INDEX idx_order_product_id 
  ON "order_items" ("product_id");

-- Webhooks (for processing queue)
CREATE INDEX idx_webhooks_processed 
  ON "stripe_webhook_events" ("processed", "received_at");

CREATE OR REPLACE FUNCTION auto_update_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  return NEW;
END;
$$ language 'plpgsql';


-- TRIGGERS FOR AUTO UPDATE_AT 
CREATE TRIGGER update_users_update_at
  BEFORE UPDATE ON "users"
  FOR EACH ROW EXECUTE FUNCTION auto_update_at_column();

CREATE TRIGGER update_addresses_update_at
  BEFORE UPDATE ON "addresses"
  FOR EACH ROW EXECUTE FUNCTION auto_update_at_column();

CREATE TRIGGER update_categories_update_at
  BEFORE UPDATE ON "categories"
  FOR EACH ROW EXECUTE FUNCTION auto_update_at_column();

CREATE TRIGGER update_products_update_at
  BEFORE UPDATE ON "products"
  FOR EACH ROW EXECUTE FUNCTION auto_update_at_column();

CREATE TRIGGER update_reviews_update_at
  BEFORE UPDATE ON "reviews"
  FOR EACH ROW EXECUTE FUNCTION auto_update_at_column();

CREATE TRIGGER update_inventory_update_at
  BEFORE UPDATE ON "inventory"
  FOR EACH ROW EXECUTE FUNCTION auto_update_at_column();

CREATE TRIGGER update_orders_update_at
  BEFORE UPDATE ON "orders"
  FOR EACH ROW EXECUTE FUNCTION auto_update_at_column();

CREATE TRIGGER update_order_items_update_at
  BEFORE UPDATE ON "order_items"
  FOR EACH ROW EXECUTE FUNCTION auto_update_at_column();

CREATE TRIGGER update_carts_update_at
  BEFORE UPDATE ON "carts"
  FOR EACH ROW EXECUTE FUNCTION auto_update_at_column();

CREATE TRIGGER update_cart_items_update_at
  BEFORE UPDATE ON "cart_items"
  FOR EACH ROW EXECUTE FUNCTION auto_update_at_column();

CREATE TRIGGER update_payments_update_at
  BEFORE UPDATE ON "payments"
  FOR EACH ROW EXECUTE FUNCTION auto_update_at_column();