CREATE TYPE "user_role" AS ENUM (
  'MANAGER',
  'CLIENT'
);

CREATE TYPE "order_status" AS ENUM (
  'PENDING',
  'PAID',
  'CANCELLED',
  'SHIPPED'
);

CREATE TYPE "payment_status" AS ENUM (
  'CREATED',
  'SUCCEEDED',
  'FAILED'
);

CREATE TYPE "cart_status" AS ENUM (
  'ACTIVE',
  'ORDERED'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "role" user_role NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp
);

CREATE TABLE "addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "full_name" varchar,
  "phone" varchar,
  "street" varchar,
  "city" varchar,
  "state" varchar,
  "country" varchar,
  "zip_code" varchar,
  "is_default" boolean DEFAULT false,
  "created_at" timestamp
);

CREATE TABLE "password_resets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "token" varchar UNIQUE,
  "expires_at" timestamp,
  "used" boolean DEFAULT false
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "price" decimal,
  "is_enabled" boolean DEFAULT true,
  "category_id" int,
  "created_by" int,
  "created_at" timestamp
);

CREATE TABLE "product_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "image_url" varchar,
  "is_primary" boolean DEFAULT false
);

CREATE TABLE "likes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "product_id" int,
  "created_at" timestamp
);

CREATE TABLE "reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "product_id" int,
  "rating" int,
  "comment" text,
  "created_at" timestamp
);

CREATE TABLE "inventory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "quantity" int,
  "updated_at" timestamp
);

CREATE TABLE "carts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "status" cart_status,
  "created_at" timestamp
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" int,
  "product_id" int,
  "quantity" int
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "status" order_status,
  "total_amount" decimal,
  "created_at" timestamp,
  "shipping_address_id" int
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "product_id" int,
  "quantity" int,
  "price" decimal
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "stripe_payment_intent" varchar,
  "amount" decimal,
  "status" payment_status,
  "created_at" timestamp
);

CREATE TABLE "stripe_webhook_events" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" varchar UNIQUE,
  "event_type" varchar,
  "payload" json,
  "received_at" timestamp
);

CREATE UNIQUE INDEX ON "product_images" ("product_id", "is_primary");

CREATE UNIQUE INDEX ON "likes" ("user_id", "product_id");

CREATE UNIQUE INDEX ON "reviews" ("user_id", "product_id");

CREATE UNIQUE INDEX ON "inventory" ("product_id");

CREATE UNIQUE INDEX ON "cart_items" ("cart_id", "product_id");

ALTER TABLE "addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "password_resets" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "product_images" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "likes" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "inventory" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("shipping_address_id") REFERENCES "addresses" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");
